export enum GameSessionStatus {
  ACTIVE = 'ACTIVE',
  WON = 'WON',
  LOST = 'LOST',
}

export enum Terrain {
  BASE = 'BASE',
  CRATER = 'CRATER',
  ROCKY = 'ROCKY',
  DUST = 'DUST',
  RIDGE = 'RIDGE',
  DARK_SIDE = 'DARK_SIDE',
}

export enum RoverStatus {
  AVAILABLE = 'AVAILABLE',
  BUSY = 'BUSY',
  DAMAGED = 'DAMAGED',
  CHARGING = 'CHARGING',
}

export enum OrderUrgency {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum DeliveryStatus {
  PREPARING = 'PREPARING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum GameEventType {
  SOLAR_STORM = 'SOLAR_STORM',
  DUST_STORM = 'DUST_STORM',
  COMMUNICATION_FAILURE = 'COMMUNICATION_FAILURE',
  LUCKY_SIGNAL = 'LUCKY_SIGNAL',
  EQUIPMENT_FAILURE = 'EQUIPMENT_FAILURE',
}

export enum BusinessErrorCode {
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ROVER_NOT_FOUND = 'ROVER_NOT_FOUND',
  ORDER_ALREADY_DELIVERED = 'ORDER_ALREADY_DELIVERED',
  ORDER_NOT_AVAILABLE = 'ORDER_NOT_AVAILABLE',
  ORDER_EXPIRED = 'ORDER_EXPIRED',
  ROVER_NOT_AVAILABLE = 'ROVER_NOT_AVAILABLE',
  CARGO_TOO_HEAVY = 'CARGO_TOO_HEAVY',
  INSUFFICIENT_BATTERY = 'INSUFFICIENT_BATTERY',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  GAME_ALREADY_FINISHED = 'GAME_ALREADY_FINISHED',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  DELIVERY_NOT_FOUND = 'DELIVERY_NOT_FOUND',
  ZONE_NOT_FOUND = 'ZONE_NOT_FOUND',
}
